# Generated by Django 5.2.8 on 2025-11-22 20:24 (updated for swappable Tenant support)

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Default to the built-in Tenant when the setting is not explicitly configured.
_TENANT_MODEL = getattr(settings, "DAMSSO_TENANT_MODEL", "damsso.Tenant")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(_TENANT_MODEL),
        # Ensure Tenant.slug is finalized (varchar 63, PK) before FK columns are created.
        # Without this, post_migrate RLS signals fire between damsso migrations and block
        # tenants.0002 from cascading the slug type change through the tenant_id FK columns.
        ('tenants', '0002_subdomain_slug'),
    ]

    operations = [
        # Only created when DAMSSO_TENANT_MODEL == 'damsso.Tenant' (standalone mode).
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sso_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SSO authentication for this tenant's users",
                    ),
                ),
                (
                    "sso_enforced",
                    models.BooleanField(
                        default=False,
                        help_text="Enforce SSO authentication (disable password login)",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Primary domain for this tenant",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "signup_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
                "swappable": "DAMSSO_TENANT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="SSOProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("oidc", "OpenID Connect (OIDC)"),
                            ("saml", "SAML 2.0"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "is_tested",
                    models.BooleanField(
                        default=False, help_text="Has been successfully tested by admin"
                    ),
                ),
                (
                    "oidc_issuer",
                    models.URLField(
                        blank=True,
                        help_text="OIDC Issuer URL (e.g., https://accounts.google.com)",
                        null=True,
                    ),
                ),
                ("oidc_client_id", models.CharField(blank=True, max_length=255)),
                ("oidc_client_secret", models.BinaryField(blank=True, editable=True, null=True)),
                ("oidc_authorization_endpoint", models.URLField(blank=True, null=True)),
                ("oidc_token_endpoint", models.URLField(blank=True, null=True)),
                ("oidc_userinfo_endpoint", models.URLField(blank=True, null=True)),
                ("oidc_jwks_uri", models.URLField(blank=True, null=True)),
                (
                    "oidc_scopes",
                    models.CharField(
                        default="openid email profile",
                        help_text="Space-separated list of scopes",
                        max_length=500,
                    ),
                ),
                (
                    "saml_entity_id",
                    models.CharField(
                        blank=True, help_text="SAML Entity ID / Issuer", max_length=500
                    ),
                ),
                (
                    "saml_sso_url",
                    models.URLField(
                        blank=True, help_text="SAML Single Sign-On URL", null=True
                    ),
                ),
                (
                    "saml_slo_url",
                    models.URLField(
                        blank=True,
                        help_text="SAML Single Logout URL (optional)",
                        null=True,
                    ),
                ),
                (
                    "saml_x509_cert",
                    models.BinaryField(
                        blank=True, editable=True, null=True,
                        help_text="X.509 Certificate for SAML (PEM format, encrypted at rest)",
                    ),
                ),
                (
                    "saml_attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of SAML attributes to user fields",
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("test_results", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tested_sso_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_providers",
                        to=_TENANT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SSO Provider",
                "verbose_name_plural": "SSO Providers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=_TENANT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Invitation",
                "verbose_name_plural": "Tenant Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID from external SSO provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_users",
                        to=_TENANT_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
