# Generated by Django 5.2.8 on 2025-11-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("damsso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="signup_token",
            field=models.CharField(
                blank=True,
                help_text="Randomized token for tenant-specific signup URLs",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
