# Generated by Django 5.2.8 on 2025-11-28 19:59

import damsso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "damsso",
            "0005_alter_ssoprovider_oidc_client_secret_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoprovider",
            name="id",
            field=models.UUIDField(
                default=damsso.models.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=damsso.models.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="id",
            field=models.UUIDField(
                default=damsso.models.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="id",
            field=models.UUIDField(
                default=damsso.models.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
