# Generated by Django 5.2.8 on 2025-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "damsso",
            "0006_alter_ssoprovider_id_alter_tenant_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoprovider",
            name="protocol",
            field=models.CharField(
                choices=[("oidc", "OpenID Connect (OIDC)"), ("saml", "SAML 2.0")],
                help_text="Which SSO protocol is currently active (OIDC or SAML)",
                max_length=10,
            ),
        ),
    ]
