# Generated by Django 6.0 on 2026-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damsso', '0008_nullable_encrypted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoprovider',
            name='is_tested',
            field=models.BooleanField(default=False, help_text='Has been successfully tested by an admin'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='oidc_issuer',
            field=models.URLField(blank=True, help_text='OIDC Issuer URL (e.g. https://accounts.google.com)', null=True),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='oidc_scopes',
            field=models.CharField(default='openid email profile', help_text='Space-separated list of OIDC scopes', max_length=500),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='protocol',
            field=models.CharField(choices=[('oidc', 'OpenID Connect (OIDC)'), ('saml', 'SAML 2.0')], help_text='Active SSO protocol (OIDC or SAML)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sso_enforced',
            field=models.BooleanField(default=False, help_text='Enforce SSO — disable password login for tenant users'),
        ),
    ]
