# Generated by Django 5.2.8 on 2025-11-28 19:12

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_allauth_multitenant_sso", "0003_setup_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoprovider",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
