# Generated by Django 5.2.8 on 2025-11-28 19:52

import django_allauth_multitenant_sso.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_allauth_multitenant_sso",
            "0004_alter_ssoprovider_id_alter_tenant_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoprovider",
            name="oidc_client_secret",
            field=django_allauth_multitenant_sso.fields.EncryptedCharField(
                blank=True,
                editable=True,
                help_text="OIDC Client Secret (encrypted at rest)",
            ),
        ),
        migrations.AlterField(
            model_name="ssoprovider",
            name="saml_x509_cert",
            field=django_allauth_multitenant_sso.fields.EncryptedTextField(
                blank=True,
                editable=True,
                help_text="X.509 Certificate for SAML (PEM format, encrypted at rest)",
            ),
        ),
    ]
